version: '3.9'
services:
  tlp-database:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
  tlp-backend:
    build:
      context: .
      dockerfile: bd.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - tlp-database



